### PR TITLE
Adding MultiPoseNet

### PR DESCRIPTION
**Pull request by forkingtest**
MultiPoseNet is the state-of-the-art in MultiPerson Human Pose Estimation at Bottom-up methods.

### CODE REVIEW

**Comment by jinwchoi** [comment]
Add a conference venue if it is published.

For example,
* [Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields](https://arxiv.org/abs/1611.08050) - Z. Cao et al, CVPR2017. [[code]](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation)
like this.

**Comment by forkingtest** [comment]
I did that, it published in ECCV.

**Comment by jinwchoi** [comment]
Can you also add the name of the first author? Exactly following this format.
Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields - Z. Cao et al, CVPR2017. [code]

**Comment by forkingtest** [comment]
Of course I did it, sorry to bother you.

**Pull request merged**
